# Generated by Django 6.0.3 on 2026-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_guest',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email гостя'),
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО гостя'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон'),
        ),
    ]
