# Generated by Django 6.0.3 on 2026-05-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_extraservice_booking_extra_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа ЮKassa'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Предоплата'), ('arrival', 'Оплата при заселении')], default='arrival', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
